trigger:
    batch: true
    branches:
        include:
        - pingpong
    paths:
        include: 
        - vue-mini-project

pool:
  name: 'Azure Pipelines'


variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')] #not used
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')] #not used
  test: ""
  vmImage : 'windows-latest'

stages:
- template: templates\stage_level_templates\test_build_stage_template.yml # stage template to test, build and push
  parameters:
    projectFolder: vue-mini-project #${{variables.projectFolder}}
    buildOutputFolder: vue-mini-project/dist #${{variables.buildOutputFolder}}
    sourceFolder: $(SOURCEFOLDER) #${{variables.sourceFolder}}
    vmImageName: $(VMIMAGE)
    

- template: templates\stage_level_templates\az_deployment_stage_template.yml # stage template for azure resource deployment to Develop
  parameters:
   vmImageName : $(VMIMAGE) #${{variables.vmImage}}
   azureSubscription : shivani
   resourceGroup : "shivani"
   bicepFilePath : "Infrastructure/main.bicep"
   parameterFilePath : "Infrastructure/main.parameters.dev.json"
   jobName : "resourcedeployment"
   jobDescription : "deployemnt of resources"
   scriptType : "bash"
   environment: 'Dev'
   deploy: true

- template: templates\stage_level_templates\app_deployment_stage_template.yml #stage template for application deployment
  parameters:
    serviceConnection: "shivani"
    subscriptionId: 'Visual Studio Enterprise Subscription - (Vikas&shivani)'
    environment: 'Dev'
    appType: 'webApp'
    appName: 'commandos-dev-as'
